apiVersion: v1
kind: Service
metadata:
  name: ersena-frontend-service
spec:
  selector:
    app: ersena-frontend
  type: NodePort # Use NodePort to expose outside the cluster
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 80 # Container port
      nodePort: 30080 # Optional: You can specify a port (must be 30000-32767)