apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-db
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
  database: {{ .Values.database.name | b64enc }}
  host:     {{ .Values.database.host | b64enc }}
