services:
  - name: "user-service"
    url: "http://user-service.t-hub-dev.svc.cluster.local:8080"
    proxy:
      path: "/api/users"
      rewrite: "/users"
  - name: "tournament-service"
    url: "http://tournament-service.t-hub-dev.svc.cluster.local:8080"
    proxy:
      path: "/api/tournaments"
      rewrite: "/tournaments"
  - name: "team-service"
    url: "http://team-service.t-hub-dev.svc.cluster.local:8080"
    proxy:
      path: "/api/teams"
      rewrite: "/teams"
