# Default values for tournament-service.
replicaCount: 1
image:
  repository: ghcr.io/dispatch7478/m7011e-project/tournament-service
  pullPolicy: IfNotPresent
  tag: "e711b51773fba630c9ebc5d4b9c25f134ffe9f86"
# Database configuration
db:
  host: "postgres-service.db.svc.cluster.local"
  port: 5432
  name: "tournament_service"
  # The name of the Kubernetes secret that holds the DB credentials
  # It must have 'user' and 'password' keys
  existingSecret: "postgres-credentials"
# RabbitMQ configuration
rabbitmq:
  host: "rabbitmq-service-api.rabbitmq.svc.cluster.local"
  # The name of the Kubernetes secret that holds the RabbitMQ credentials
  # It must have 'RABBITMQ_DEFAULT_USER' and 'RABBITMQ_DEFAULT_PASS' keys
  auth:
    existingSecret: "rabbitmq-credentials"
service:
  type: ClusterIP
  port: 8080
