apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app: grafana
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: grafana
        release: {{ .Release.Name }}
      annotations:
        checksum/grafana-datasource: {{ include (print $.Template.BasePath "/grafana-datasource-config.yaml") . | sha256sum }}
        checksum/grafana-dashboard-provider: {{ include (print $.Template.BasePath "/grafana-dashboard-provider-configmap.yaml") . | sha256sum }}
        checksum/grafana-dashboards: {{ include (print $.Template.BasePath "/grafana-dashboards-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.images.grafana.repository }}:{{ .Values.images.grafana.tag }}"
          imagePullPolicy: {{ .Values.images.grafana.pullPolicy }}
          volumeMounts:
            - name: grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.grafana.adminSecretName }}
                  key: {{ .Values.grafana.adminUserKey }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.grafana.adminSecretName }}
                  key: {{ .Values.grafana.adminPasswordKey }}
      volumes:
        - name: grafana-datasource
          configMap:
            name: {{ .Release.Name }}-grafana-datasource
        - name: grafana-dashboard-provider
          configMap:
            name: {{ .Release.Name }}-grafana-dashboard-provider
        - name: grafana-dashboards
          configMap:
            name: {{ .Release.Name }}-grafana-dashboards
