apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tournament-service.fullname" . }}
  labels:
    {{- include "tournament-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tournament-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tournament-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            # --- Database Config ---
            - name: DB_HOST
              value: {{ .Values.db.host | quote }}
            - name: DB_PORT
              value: {{ .Values.db.port | quote }}
            - name: DB_NAME
              value: {{ .Values.db.name | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: password

            # --- RabbitMQ Config ---
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | quote }}
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.auth.existingSecret }}
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.auth.existingSecret }}
                  key: RABBITMQ_DEFAULT_PASS
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health   # or /ready if you implement it
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
