apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dispatch7478/m7011e-project.git 
    targetRevision: main
    # Point to the folder where the chart lives
    path: k8s/charts/hello-service 
  destination:
    # Deploy into the cluster Argo is running in
    server: https://kubernetes.default.svc
    # Deploy to the dev env
    namespace: t-hub-dev 
  
  # Enable "GitOps" automation
  syncPolicy:
    automated:
      prune: true    # Delete resources if I delete them from Git
      selfHeal: true # Fix the cluster if someone manually breaks it
    syncOptions:
      - CreateNamespace=true # Create the namespace if it doesn't exist