apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dispatch7478/m7011e-project.git
    targetRevision: HEAD
    path: k8s/charts/team-service # Path to the team-service Helm chart
  destination:
    server: https://kubernetes.default.svc
    namespace: t-hub-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
