replicaCount: 1
image:
  repository: ghcr.io/dispatch7478/m7011e-project/team-service
  tag: cda3d3edae5b392f1ad903bf28d194043aec44d9
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
database:
  host: "postgres-service.db.svc.cluster.local"
  name: "team_service"
  existingSecret:
    name: "team-service-db"
    usernameKey: "DB_USERNAME"
    passwordKey: "DB_PASSWORD"
resources: {}
