apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bracket-service.fullname" . }}
  labels:
    {{- include "bracket-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bracket-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bracket-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            # --- Database Config (All from Secret) ---
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: DB_HOST
            - name: DB_PORT
              value: "5432" # Hardcoded atm
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: DB_PASS

            # --- RabbitMQ Config ---
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | quote }}
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.auth.existingSecret }}
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.auth.existingSecret }}
                  key: RABBITMQ_DEFAULT_PASS
            
            # --- Other Environment Variables ---
            - name: TOURNAMENT_SERVICE_URL
              value: {{ .Values.env.TOURNAMENT_SERVICE_URL }}