# Default values for rabbitmq-test.
replicaCount: 1

image:
  repository: ghcr.io/dispatch7478/m7011e-project/rabbitmq
  pullPolicy: IfNotPresent
  tag: ""

# Configuration for connecting to RabbitMQ
rabbitmq:
  # The host of the RabbitMQ service. This should be the FQDN of the service in the other namespace.
  host: "rabbitmq-service-api.rabbitmq.svc.cluster.local"
  
  # The name of the Kubernetes secret that contains the RabbitMQ credentials.
  # This secret must exist in the same namespace where this chart is deployed (e.g., t-hub-dev).
  auth:
    existingSecret: "rabbitmq-credentials"

service:
  type: ClusterIP
  port: 8080
